name: Integration

on: push

jobs:
  integration:
    runs-on: ubuntu-18.04

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo add-apt-repository -y ppa:git-core/ppa
        sudo apt-get install -y git gradle jq
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Run gradle command
      run: |
        gradle build
